### ISSUE TITLE
CDL Support

### ISSUE THREAD

**Issue by jonjonreidreid** [videovillage/Lattice-Issues#10]
I think ASC CDL support would be great. The ability to combine LUTs + CDL would be a great tool.

**Comment by gregcotten** [comment]
@timkang1980 @error1k @jonjonreidreid 

Finally got around to implementing this. We can now parse CDLs from ALE, FLEx, CMX EDL, CC, CCC, and CDL and apply them (Prepend or Append) to any LUT.

![screen shot 2015-01-27 at 10 44 12 am](https://cloud.githubusercontent.com/assets/924470/5924552/a3d30f5e-a611-11e4-8aee-e33a75598253.png)
