### ISSUE TITLE
import ALE with CDL from Resolve crashes Lattice

### ISSUE THREAD

**Issue by MorphImaging** [videovillage/Lattice-Issues#100]
I've done this successfully on a previous project, but it's not working now.

Every time I try to import (via open LUT option) an ALE with CDL into Lattice it crashes. I'm positive that's how I did it before.

I'm exporting from Resolve project (17.3.1). 

Any idea what's going on here? I'm guessing something to do with the formatting of the ALE is throwing Lattice off. Or did this functionality get removed from Lattice?

Any help gratefully received.

Best,
Chris

**Comment by gregcotten** [comment]
Hey! What version of macOS are you running? It should be working just fine.

**Comment by gregcotten** [comment]
I just updated Lattice (1.8.19) to hopefully fix this issue on old macOS versions.
