### ISSUE TITLE
Custom Transfer Functions

### ISSUE THREAD

**Issue by timkang1980** [videovillage/Lattice-Issues#16]
Can you guys build in support for manual entry of equations (expressions in Nuke)?

**Comment by gregcotten** [comment]
@timkang1980 

We support CTL now - any chance this solves your issue?

**Comment by timkang1980** [comment]
Thanks for adding this in. I'm just trying to figure out - what's the math syntax for applying an expression? is it all python format?

**Comment by gregcotten** [comment]
You can find more info on how expressions work [here](https://github.com/davedelong/DDMathParser/wiki/Functions). If you want to use CTL, here is an example in = out script:

```c
void main 
(
    input varying float rIn, 
    input varying float gIn, 
    input varying float bIn, 
    input varying float aIn,
    output varying float rOut,
    output varying float gOut,
    output varying float bOut,
    output varying float aOut
)
{
    rOut = rIn;
    gOut = gIn;
    bOut = bIn;
    aOut = aIn;
}
```
