### ISSUE TITLE
Package export

### ISSUE THREAD

**Issue by QuentinBrown** [videovillage/Lattice-Issues#28]
Sometimes it is not known what system the finishing will take place on at the time we shoot and create LUT's on set. A feature to export a package of LUTs (one version in each format that the program supports) would be very handy. 
This would be great also if it could be combined with the batch processing options also requested.

**Comment by jbowdach** [comment]
Second this, or ability to export with multiple formats (user selectable)

**Comment by gregcotten** [comment]
@jbowdach @QuentinBrown 

Forgot to close this - implemented and released this today! Should be on the App Store sometime next week.

Greg
