### ISSUE TITLE
EXR Support for preview Images

### ISSUE THREAD

**Issue by mwright554** [videovillage/Lattice-Issues#33]
Whenever I open an exr into lattice to view it with a LUT it doesn't display properly in the window at all.  This is very important because I basically almost exclusively work in EXR's and I want to be able to use this software to create the images I need.

**Comment by gregcotten** [comment]
@mwright554

Currently there is no official support for the OpenEXR format in Lattice. We are working on EXR in conjunction with tetrahedral interpolation for the next release! The only reason Lattice can read an EXR at the moment is because OS X can natively open them (albeit with incorrect color management).

**Comment by mwright554** [comment]
Thanks for the quick response.  Do you guys have an expected release time for this upcoming update?  When can I expect to be able to use this feature in the app?

**Comment by gregcotten** [comment]
@mrwright554

Probably within a month. Just out of curiosity what is your use case for Lattice? You are the first user to talk about EXR.

**Comment by mwright554** [comment]
I work at a VFX house.  So we need to take LUT's generated by the DI facility and convert them to get them to work within our pipeline in Flame, Nuke, Nucoda and all of our other programs.  We've been using Nuke to convert them, but it has some limitations that stop us and it can make things more complicated than it needs to be.  That is why we are trying Lattice  We work exclusively in Linear 16 bf EXR files and need to have versions of LUT's to work correctly in all of our software.

We've lately had some shows want to use EXR's through the entire pipeline too and once ACES finally takes over we'll be ready because we are basically already there.

**Comment by gregcotten** [comment]
@mwright554 

After some furious coding I now have preliminary EXR/Scene Linear support in Lattice.

What kind of LUTs are you dealing with generally and what are your conversion goals? 

Dealing with Scene Linear -> Display referred LUTs often requires the use of a shaper LUT + a 3D LUT of some sort. Currently Lattice doesn't support the editing of this "hybrid" form of LUT and instead works with just 3D and 1D LUTs independently. As far as I know flame would require a separate shaper and 3D LUT.

Greg

**Comment by gregcotten** [comment]
@mwright554 

We have included OpenEXR support in Lattice 1.2.8 - it is now released for FSI customers and is awaiting approval on the App Store. Please be advised that you will need OS X Yosemite to get proper OpenEXR support as Mavericks had some issues with the format.

Greg
