### ISSUE TITLE
1.2.9 crashing with any 1D operation

### ISSUE THREAD

**Issue by andyp6** [videovillage/Lattice-Issues#34]
Hi Greg,

I'm running Lattice on a VirtualBox (Mavericks) and apart from the missing 3D view of the cube (GPU hardware VBox restriction) Lattice has been working well. 

I updated to 1.2.9 today and it crashes with any 1D operation (creating a 1D lut, converting a 3D lut to 1D etc). 3D operations seem to be unaffected. I'm not sure if it's VBox related because it's been ok up to today.

Crash log: https://gist.github.com/andyp6/a0ad53c1b5ca2a4e7a35

**Comment by wilg** [comment]
@gregcotten Should that be `kernelsWithString` (plural)?

**Comment by gregcotten** [comment]
@wilg Apparently 10.9 doesn't have a kernelWithString but 10.10 does.

@andyp6 We'll get this patched right away. Sorry for the inconvenience.
