### ISSUE TITLE
selecting 1D luts in 1.2.9 immediately crashes Lattice

### ISSUE THREAD

**Issue by goatride** [videovillage/Lattice-Issues#35]
I open Lattice, select 1D lut (any size) hit "create" crash - o - rama
mac pro 12 core / os 10.9.5

**Comment by goatride** [comment]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[CIKernel kernelWithString:]: unrecognized selector sent to class 0x7fff712e3f60'
terminating with uncaught exception of type NSException
abort() called

**Comment by gregcotten** [comment]
@goatride 

Sorry about that! 1.2.9 broke legacy compatibility with Mavericks - the next release fixes this issue and should be coming out this week.

duplicate ref: https://github.com/videovillage/Lattice-Issues/issues/34

**Comment by goatride** [comment]
wow mavericks is already “legacy”? man...
OS 9, Mavericks, yeah all the old school stuff.
so if i’m in Yosemite I’m good?

4K Finish | Paul Provost - owner/colorist
323-365-1221 | www.4KFinish.com | Los Angeles, CA

**Comment by gregcotten** [comment]
@goatride

I just meant for backwards compatibility! I understand that some need to stay on Mavericks until certain applications catch up with the new OS. Yes, if you're on Yosemite this will not be a problem - but the next update will fix this for Mavericks.
