### ISSUE TITLE
feature request: Assimilate Scratch support

### ISSUE THREAD

**Issue by lejeunecedric** [videovillage/Lattice-Issues#36]
Hi, 
Scratch has its own view on .3dl, which is generally a 32 size version. Can pass you the header if you want (I also have tons of other formats if required).

**Comment by gregcotten** [comment]
@lejeunecedric

Please do pass along a complete Assimilate Scratch .3dl if you don't mind! 

We've mainly been adding formats as people request them so we don't end up wasting time on formats that people don't use or needs.

**Comment by lejeunecedric** [comment]
Here you go!

2015-02-09 17:13 GMT+01:00 Greg Cotten <notifications@github.com>:

**Comment by gregcotten** [comment]
@lejeunecedric

Unfortunately GitHub doesn't take email attachments... Perhaps a dropbox link?

**Comment by lejeunecedric** [comment]
sure thing! https://www.dropbox.com/s/113acc4uvtknvxy/ScratchLUT.3dl?dl=0

**Comment by gregcotten** [comment]
@lejeunecedric 

This seems to open fine in Lattice. It's identified as a "Nuke" file type variant but seems to be identical.

**Comment by lejeunecedric** [comment]
Yes but can't save as this format, can I?

2015-03-03 8:13 GMT+01:00 Greg Cotten <notifications@github.com>:

**Comment by gregcotten** [comment]
@lejeunecedric

You can by saving out a 16-bit 3DL.
