### ISSUE TITLE
format support: Autodesk Lustre 16 bit 1D LUT

### ISSUE THREAD

**Issue by lejeunecedric** [videovillage/Lattice-Issues#37]
another one that would be really handy, the Autodesk Lustre 1D 16 bit format
here's an example https://www.dropbox.com/s/qne4h7s02odpq8o/lintolog16bit2_2.lut?dl=0
Thanks!
Cedric

**Comment by gregcotten** [comment]
@lejeunecedric 

Do you know if it only does 16-bit or if there are other bit-depth options?

**Comment by lejeunecedric** [comment]
there are a lot of formats for Lustre, more or less documented, 16 bit is the one you really want :)

**Comment by gregcotten** [comment]
@lejeunecedric 

Just to be feature-complete I would like to see any other variations on the format. I'm assuming there is ```LUT10 from 10``` or ```LUT12 from 12```?

**Comment by lejeunecedric** [comment]
Hi Greg,

that would be too simple :)
There's:
""""""""""""""""""""""""""""""""""""
LUT8

#
# LUT to convert 10-bit log to 8
# RGB Reference White: 685 685 685
# RGB Reference Black: 95 95 95
# RGB Softclip:    0 0 0
# RGB Film Gamma: 0.6 0.6  0.6

0 0 0 0
1 0 0 0
2 0 0 0
3 0 0 0
4 0 0 0
5 0 0 0
6 0 0 0
...
""""""""""""""""""""""""""""""""""""
LUTDensity 1.0
0 4.30 3.94 3.71
25 4.30 3.93 3.70
50 4.26 3.88 3.67
75 4.22 3.81 3.60
...
""""""""""""""""""""""""""""""""""""
LUT10

0 94 94 94
1 106 106 106
2 116 116 116
3 126 126 126
4 134 134 134
5 143 143 143
6 151 151 151
7 158 158 158
8 165 165 165
...
""""""""""""""""""""""""""""""""""""

That's what I have in my records, there might be other even more obscure!

Best,
Cedric


2015-04-20 18:58 GMT+02:00 Greg Cotten <notifications@github.com>:
