### ISSUE TITLE
Format Support Request: LUT to Arri Alexa Look XML

### ISSUE THREAD

**Issue by cubanb31** [videovillage/Lattice-Issues#38]
I didn't see this option in the LUT export list, but would it be possible to add an export option for "Alexa Look (.xml)"? I only see one for Amira.

I'm trying to take 3d LUTS created in Resolve and load them onto the Alexa.

Thanks!

**Comment by gregcotten** [comment]
Hi there,




Only 1D LUTs are supported by the Alexa Look XML specification. You must first convert to a 1D LUT and then use Save As or Export to save out an Alexa Look XML.




Greg

**Comment by cubanb31** [comment]
Thanks!
