### ISSUE TITLE
BUGs experienced

### ISSUE THREAD

**Issue by talazar** [videovillage/Lattice-Issues#39]
Hello,

Yesterday I used Lattice to demonstrate an easy way to create LUTs to students.
File following problems occurred:
- The program crashes when color space conversion LUT is applied AFTER I drag a DPX file to replace the default image. The program does not crash when the LUT is created first and the DPX is dragged later. This has occurred on two different computers (MacPro with Blackmagic hardware and software & iMac 27" home with no additions) and seems to be a consistent issue on this end, even after the latest update.
- LUTs created with Lattice with 'Resolve' file type seem to deviate slightly from the normal 'Resolve' LUT specification - just enough to crash Sony cameras trying to use these LUTs as camera LUTs. They may work for other programs but Sony has not made the F55 (this is the camera in which this was tested) flexible enough to overlook slight differences - even a newline or character out of place. This difference in the header of the file is easily fixed manually but the program can export properly instead.

Otherwise great piece of software, keep on the good work!

Thanks,

Tal Lazar

**Comment by gregcotten** [comment]
@talazar 

Hi Tal,

1. Thanks for pointing that weird issue out! It was a really silly and simple bug to fix. I will push an update sometime today fixing it.

2. The "Resolve Legacy" export type seems to work perfectly on F55 and F5 cameras. I didn't think the Sony camera would even take the "Resolve" type which has 10 digits of precision after the decimal - what did you do to make it work?
