### ISSUE TITLE
Manually adjust curves

### ISSUE THREAD

**Issue by jimwicks** [videovillage/Lattice-Issues#40]
Output to my calibrated grading monitor would be a nice touch.

Is there a feature that allows me to manually adjust the curves?
If not, is this a feature worth adding?

Thanks.

Jim

**Comment by gregcotten** [comment]
@jimwicks 

1. Certainly on the docket but harder than it sounds. Do you have BMD hardware? BMD hardware SDI out is the first on our list for pro i/o.

2. We try to distance ourselves from "color grading" tools. This kind of tool probably falls in a grey area between technical and creative. Certainly worth exploring.

**Comment by jimwicks** [comment]
Yes BMD hardware with an SDI out. I'm not looking at this as a traditional color tool. Rather, I want to use it as a comparison of how the LUT and the changes that I make fit within my workspace environment. My grading monitor is where my work lives - so seeing the LUT with its changes in this ecosystem will help determine whether I accept the changes that I make to the LUT. Does that make sense? 
So it is possible?

**Comment by gregcotten** [comment]
@jimwicks 

Yes, this is the case for most of our users - for whatever reason SDI out is not a hotly requested feature - we've just had a few ask for it. In any case it is on our radar!

Thanks,
Greg

**Comment by gregcotten** [comment]
@jimwicks 

My initial #2 response was directed at your curves adjustment question - not the SDI out question.

Greg

**Comment by frankjonen** [comment]
Manually adjusting curves would be great for quick fixes where everything else works fine but some odd bit just causes issues. Even if it's just a task like removing 'stray' points, select in and out points, and have the removed ones interpolated to a smooth curve with an 'interpolate between selected' tool.

**Comment by wilg** [comment]
Split the issue into #40 and #83.
