### ISSUE TITLE
Monochrome from Secondary Colors

### ISSUE THREAD

**Issue by NickyKing415** [videovillage/Lattice-Issues#41]
Would it be easy to add secondary colors to the monochrome conversion? How about tertiary colors or custom colors for the conversion?

**Comment by gregcotten** [comment]
Hi @NickyKing415,

Not familiar with converting to monochrome using those methods - can you lend any insight as to how the math works for secondary or tertiary colors?

**Comment by NickyKing415** [comment]
Hey! Thanks for the quick reply.

I'm not sure about the maths behind it but when I would shoot in black and white I would often use a yellow filter to bring out the highlights. You have red and green already which are also great filters for B&W.

Often times we use off colors in color correction to convert to B&W because it brings out skin tones or increases latitude.

Just was wondering if it was an easy option to add. Thanks!

--
Nicholas Finn Myggen
Director of Photography
c.415.990.7467
g.415.729.3729
nick@myggen.com
