### ISSUE TITLE
Feature Request: axis labels for curves

### ISSUE THREAD

**Issue by nick-shaw** [videovillage/Lattice-Issues#42]
Because Lattice scales the curve display depending on the LUT's input and output range, it can be hard to compare the curves of two different LUTs. Even just bolder lines representing 0.0 and 1.0 would be a useful reference.

It would also be useful to have a "reset scale" button for the curves to set the scaling to a standard range of 0.0-1.0 for input and output. That way you could have two LUTs open which had different ranges, but compare the curves easily (I like to align the two windows on top of one another and flip between them.)

EDIT: Sorry, I just realised this is a duplicate request. But my reset button is an additional one!

**Comment by gregcotten** [comment]
Nick,




That’s a great idea. I’ve been meaning to do some work on the Curves view for a while now!
