### ISSUE TITLE
Support .cube LUTs from AmiraColorTool

### ISSUE THREAD

**Issue by photonclock** [videovillage/Lattice-Issues#44]
3x32 cube LUT from AmiraColorTool width unrecognized.

Example:
```
# Truelight Cube v2.0
# iDims     3
# oDims     3
# width     32 32 32

# Cube
0.000000 0.000000 0.000000
0.000240 0.000039 0.000047
0.001604 0.000032 0.000093
0.004993 0.000000 0.000008
0.011122 0.000000 0.000000
0.020743 0.000000 0.000000
...etc...
```

Appending this line:
```
LUT_3D_SIZE 32
```
after the #width line enables Lattice to parse the LUT.

**Comment by gregcotten** [comment]
It's really strange they aren't using the (much more popular) Resolve cube format.

**Comment by gregcotten** [comment]
Looks like there are a lot of format options for exporting out of the Amira Color Tool. I would recommend using the "DaVinci Resolve" format!

![screen shot 2015-07-05 at 2 23 46 pm](https://cloud.githubusercontent.com/assets/924470/8513033/8da8cf2e-2321-11e5-8486-1e3a7dbcde7c.png)
