### ISSUE TITLE
Luminance Sub Ranges

### ISSUE THREAD

**Issue by giardiello** [videovillage/Lattice-Issues#45]
Hi,
it would be nice if it will be possible to convert Data to Video LUT's or viceversa.
It might be created as a 1D LUT and then appended to a 3D LUT already existing. 

Best regards,
F

**Comment by gregcotten** [comment]
Hi @giardiello, you can currently scale Legal to Full and Full to Legal under Edit->Scale.

**Comment by giardiello** [comment]
Oh gosh, yep...so sorry...I haven't seen the whole EDIT menu (just got the software). Sorry!

**Comment by gregcotten** [comment]
@giardiello No worries! Happy to help
