### ISSUE TITLE
Baselight .cube Support

### ISSUE THREAD

**Issue by clintonhomuth** [videovillage/Lattice-Issues#46]
Could we get .cube support?

Thanks!

**Comment by gregcotten** [comment]
Any chance you have a spec for Baselight's .cube format? I can find examples but can't find a document with the spec.

**Comment by clintonhomuth** [comment]
This work for you?

**Comment by gregcotten** [comment]
Unfortunately no, attachments don't work on GitHub.

**Comment by clintonhomuth** [comment]
Artists House 14-15 Manette St London, W1D 4AP UNITED KINGDOM

t: +44 (0)20 7292 0400 f: +44 (0)20 7292 0401 www.filmlight.ltd.uk

Technical Note

Truelight Cube Format 2.1

Richard Kirk

Summary

This document describes the Truelight cube format.

The 2.1 cube format is mostly compatible with the earlier 2.0 cube format. The only differences in 2.1 are in how the out of range floating point values are handled.


Document ref.

FL-TL-TN-0374-TLCubeFormat2.1

Creation date

Richard Kirk

Last modified

24 July 2013

Revision no.

1.0

1 Format description

The Truelight cube is a human-readable file containing colour transform data for processing image pixel data like this...

FL-TL-TN-0374-TLCubeFormat2.1

2


Truelight Cube Format 2.1

 
1D LUT

     
1D LUT

    
4D to 4D render table


1D LUT

     
1D LUT

    
The format can support up to four input dimensions and up to four output dimensions. There is no limit to the size of the 1D LUTs or the render table in the format, but some GPU hardware cannot support LUTs larger than 8K, or cubes with more than 255 intervals. For most Truelight work, we use three inputs and three outputs, a 101 entry input LUT (1% intervals) and a 16x16x16 render table. We find that 16 intervals is generally enough if you use the 1D input LUTs to linearise the transform. The Truelight hardware is limited to three inputs, three outputs, and a 16x16x16 render table.

There are also special cases for the format where we omit the 1D LUTs, or the render table. These are described in the examples later in this note.

The data in the file is written as floating-point values. If your inputs or outputs are unsigned integer values, these values are scaled so the floating point value 1.0 represents the maximum unsigned integer value. A cube file may contain values outside the range 0.0 to 1.0, but the values will be clipped to the working range of your image data. If you are working with floating point images, the current format cube can be used to transform image values in the range 0.0 to 1.0, and to extrapolate a short way beyond this range.

Cube files should be laid out like one of the examples in this note. The lines should contain the right entries, and blocks of data should not be interrupted by extra blank lines. Lines should be terminated using the Unix '\n' character (0x0A), though readers may support the old MacOS and MS-WIndows line termination options. The exact spacing and formatting within lines is usually not important: leading and trailing spaces are ignored, and you may replace spaces with tabs. Floating point numbers may include exponents.


Revision 1.0, 24 July 2013

Truelight Cube Format 2.1

A simple Truelight cube with an input LUT and a 6x6x6 render table that leaves the data unchanged looks like this...

Notes:

The header tells us this is a cube file with an input LUT of length 11, three input values, three output values, and a 6x6x6 render table. Up to four inputs and outputs are supported. A typical cube will have an input length of 101 (1% intervals) and a 16x16x16 render table.

Extra blank lines are ignored.

There are three sets of input LUTs, one for each input, ranged from 0-5 in this case as the values are in units of cube intervals.

The data should be laid out as shown. The indentation and formatting of the floating-point numbers is not important, but you must have the right number of entries per line. Blank lines after the data are ignored.

The floating-point input LUT is typically used to interpolate a higher precision LUT matched to the particular input image data format. The LUT here has uniform intervals, so we could have used a shorter LUT, omitting all but the first and last values. Typical LUTs have uneven intervals. Truelight adjusts the LUT intervals to keep the interpolation smooth.

Here is the cube render table data. The values are ordered with the first value (red) changing fastest and the last value (blue) changing slowest.

The data should be laid out as shown. The indentation and formatting of the floating-point numbers is not important, but you must have the right number of entries per line.

Blank lines after the data are ignored.

The values can go outside the 0.0-1.0 range. The rendering software may clip these values when they make a run-time render table matched to the image data format.

Any data following this line is ignored. This is a good place to stick any useful information on the cube generation.

# Truelight Cube v2.1
# lutLength 11
# iDims
# oDims
# width
3
3
6 6 6

# InputLUT
 0.000 0.000 0.000
 0.500 0.500 0.500
 1.000 1.000 1.000
 1.500 1.500 1.500
 2.000 2.000 2.000
 2.500 2.500 2.500
 3.000 3.000
 3.500 3.500
 4.000 4.000
 4.500 4.500 4.500
 5.000 5.000 5.000
# Cube
 0.0 0.0 0.0
 0.2 0.0 0.0
 0.4 0.0 0.0
  ( 210 lines omitted )
 0.6 1.0 1.0
 0.8 1.0 1.0
 1.0 1.0 1.0
# end

3.000
3.500
4.000
FL-TL-TN-0374-TLCubeFormat2.1

3

 
Revision 1.0, 24 July 2013

You can make cubes without input LUTs and cubes without render tables. Here is a simple example of a cube without a render table...

# Truelight Cube v2.1
# lutLength 11
# iDims     3
# InputLUT
 0.000 0.000 0.000
 0.100 0.100 0.100
 0.200 0.200 0.200
 0.300 0.300 0.300
 0.400 0.400 0.400
 0.500 0.500 0.500
 0.600 0.600 0.600
 0.700 0.700 0.700
 0.800 0.800 0.800
 0.900 0.900 0.900
 1.000 1.000 1.000
# end

The header tells us this is a cube file with an input LUT of length 11, and three input values. The number of output values must be the same as the number of input values.

There are the three sets of input LUTs, one for each input.

The input LUT is used to interpolate a higher precision LUT matched to the particular image format. For integer formats, the range 0-1 is mapped onto the integer range. Floating point values outside the 0-1 range are allowed but may be truncated for integer formats.

Any data following this line is ignored.

Here is a simple example of a cube with a render table but no LUT...

# Truelight Cube v2.1
This time we have omitted the lutLength option and the LUT. This is equivalent to having a linear LUT that covers the whole cube range.

Here is the cube render table data. The values are ordered with the first value (red) changing fastest and the last value (blue) changing slowest.

The values can go outside the 0.0-1.0 range. The rendering software may clip these values when they make a run-time render table matched to the image data format.

Any data following this line is ignored.

# iDims
# oDims
# width
# Cube
 0.0 0.0 0.0
 0.2 0.0 0.0
 0.4 0.0 0.0
3
3
6 6 6

  ( 210 lines omitted )
 0.6 1.0 1.0
 0.8 1.0 1.0
 1.0 1.0 1.0
# end

FL-TL-TN-0374-TLCubeFormat2.1

4


Truelight Cube Format 2.1


Revision 1.0, 24 July 2013

2 Floating-point support

The Truelight 2.1 standard supports floating-point spaces by adding some optional extra LUTs...

FL-TL-TN-0374-TLCubeFormat2.1

5


Truelight Cube Format 2.1

1D float input gamut LUT

  
1D LUT


1D LUT

4D to 4D render table

1D float output gamut LUT

     
1D LUT

    
1D LUT

        
A simple Truelight cube with an input LUT and a 6x6x6 render table that leaves the data unchanged looks like this...

# Truelight Cube v2.1
# inLength  6
# lutLength 11
The header has an extra inLength field which gives the length of the input gamut LUT.

This table contains the input floating-point values that are mapped onto the ordinary 0-1 gamut. In this case we have linearly mapped the range 0.0 to 2.0. The values can be negative but should be all be real numbers in increasing order.

The intervals do not need to be uniform. You can use this LUT to linearise non-uniform spaces. You will probably want a much larger LUT to do this.

This table is the wrong way around for the data flow in the previous diagram. The software that applies the cube will probably take this table and combine it with the input LUTs to make a single set of 1D LUTs that transform half-precision floats to cube intervals and fractions.

This is the same as the first example. This LUT will probably be combined with the input gamut LUT when the cube is loaded.

This is the same as the first example.

Any data following this line is ignored.

# iDims
# oDims
# width
# InGamut
 0.000000
 0.400000
 0.800000
 1.200000
 1.600000
 2.000000
3
3
6 6 6

# InputLUT
 0.000 0.000 0.000
 (9 lines omitted)
 5.000 5.000 5.000
# Cube
 0.0 0.0 0.0
  ( 214 lines omitted )
 1.0 1.0 1.0
# end


Revision 1.0, 24 July 2013

Truelight Cube Format 2.1

Output gamut LUTs can be used in a similar way to expand the range of the output.

These are less common because we are often applying a LUT to rendered float image data to view it on a device with a fixed RGB range. However, we can use this to convert the output to non-perceptual spaces such as RGB luminance.

Here is an example of a cube with an output gamut LUT...

# Truelight Cube v2.1
# lutLength 11
The header has an extra outLength field which gives the length of the output gamut LUT.

This is the same as the first example.

This is the same as the first example.

The ordinary 0-1 output gamut is mapped onto the values in this table. In this case we have linearly mapped the range 0.0 to 2.0. The values can be negative but should be all be real numbers in increasing order.

The intervals do not need to be uniform. You can use this LUT to linearise non-uniform spaces. You will probably want a much larger LUT to do this.

The cube software should not combine this table with the cube values. That would give approximately the same result for less processing, but it will give a less smooth transform.

Any data following this line is ignored.

# iDims
# oDims
# width
# outLength 11
# InputLUT
 0.000 0.000 0.000
 (9 lines omitted)
 5.000 5.000 5.000
# Cube
 0.0 0.0 0.0
  ( 214 lines omitted )
 1.0 1.0 1.0
# OutGamut
 0.000000
 0.200000
 0.400000
 0.600000
 0.800000
 1.000000
 1.200000
 1.400000
 1.600000
 1.800000
 2.000000
# end

3
3
6 6 6

Note: we can omit the InputLUT field or the Cube field as we did in the previous section.

FL-TL-TN-0374-TLCubeFormat2.1

6

 
Revision 1.0, 24 July 2013

3 Notes

  The 2.1 cube format is compatible with the earlier 2.0 cube format. The only differences are the additions to support floating point gamuts.

  The 4D inputs and outputs are rarely used. You can provide support for the Truelight cube format without having to support these.

  The number of intervals in the render table is almost always the same for each channel. The Truelight library only supports one render table size parameter. However, you could make a 16x16x16x2 cube from two 16x16x16 cubes using a text editor, and it should work.

  The input and output spaces are typically device RGB. However, there is nothing in the format forcing the requiring the channels to be red, green, blue in that order.

  The Truelight library does the render interpolation using the pyramidal interpolation algorithm. We believe this provides a smoother interpolation for the neutrals than the more common trilinear algorithm. The user is free to use any algorithm they like.

  The Truelight library will by default generate cubes where the input LUTs will give uniform steps in the output along the diagonal. This usually gives a good result for much less render table intervals. Truelight has the option for using more intervals, but this is rarely helpful. It is possible to construct pathological cases that require more than 16 intervals, but these are rare, and when they happen, using more intervals rarely helps much.

  The ordering of values in the Truelight cube is not in the same order as a C++ array order. Our first parameter varies fastest, whereas most other cubes vary the last parameter fastest.

  When we have 1D LUTs and a render table, the outputs of the render table are listed in cube intervals. This aided debugging, and allowed us to accurately index a particular cube level. Most GPU render tables these days are ranged 0.0 - 1.0.

  The cube file format has no formal limits on lutLength and cube width, but some GPU hardware cannot support LUT sizes of 8K and above. If you have a 16-bit LUT, and you have cast it into the FilmLight cube format, this may work in the Truelight viewer in CPU mode, but may give unexpected results on the GPU depending on your hardware and software version. If you are having problems, you can resize your LUTs and cube using 'tl-utils ResizeCube'.

FL-TL-TN-0374-TLCubeFormat2.1

7


Truelight Cube Format 2.1


Revision 1.0, 24 July 2013

**Comment by gregcotten** [comment]
would you mind sending the document to support@videovillage.co? Thanks!
