### ISSUE TITLE
Add support for creating "neutralizing" LUTs from Chip Chart images

### ISSUE THREAD

**Issue by gregcotten** [videovillage/Lattice-Issues#48]

**Comment by joe12south** [comment]
I second this motion.

**Comment by frankjonen** [comment]
Yes please!

**Comment by QuentinBrown** [comment]
As a side feature, and maybe easier to implement as you won't have to manually map the chips to be analysed to the portions of the captured image, would be the ability to generate a LUT from a processed digital chip chart. The source chip chart would have to be supplied as a file with Lattice, then when say a stills editor is used to create a look that it cannot export as a 3DLUT you can put the chip chart image through the same process in that software, output it and have lattice analyse the difference from the original reference and generate a 3DLUT. Being able to process a batch of these images into LUT's could also be very useful.

**Comment by gregcotten** [comment]
Quentin,

This feature is already supported actually and is “batchable” as well. Just
export an identity 3D LUT as an “Unwrapped Cube Image”, “CMS Test Pattern”
or “HALD CLUT” - it creates a .tiff image representation of a 3D LUT that
you can then process through an application that doesn’t support 3D LUT
creation. You can then open that back up in lattice or simply drag and drop
into the batch exporter.

**Comment by QuentinBrown** [comment]
This is excellent news. Very glad this feature is already here and I didn't realise.
It would be great if someone out there produced a calibrated printed chart like a HALD CLUT (maybe backlit?) with a full gamut to match ACES if such a thing were possible. Then we could film/photograph it and generate all sorts of camera matching, film stock & process matching & correcting LUTs.
