### ISSUE TITLE
Autodesk CTF File Format Version 1.3 support

### ISSUE THREAD

**Issue by pamerico** [videovillage/Lattice-Issues#50]
Could you implement this? Now that we have flame on Mac OSX this would be very useful. Thanks.

http://docs.autodesk.com/smoke2015-user-guide/index.html?url=files/GUID-43589612-96FC-425E-A150-F2BFC364D7D7.htm,topicNumber=d30e114778

**Comment by gregcotten** [comment]
A big issue here is that most of the ops in their standard have proprietary color math in them!
