### ISSUE TITLE
CTL files don't work since 1.5.3 update

### ISSUE THREAD

**Issue by Nick-Shaw** [videovillage/Lattice-Issues#51]
It is of course possible something else has changed on my Mac, and it's not a Lattice issue, but prior to updating to 1.5.3 (Mac App Store version) applying CTL worked fine for me, and I was able to test a CTL file I was writing by dragging it into the Lattice "Apply CTL" panel. It was a useful way of debugging my CTL, as if I had a syntax error, Lattice would not accept the file.

Since the 1.5.3 update I cannot drag any CTL files in, including the standard Academy ones, and my custom ones which previously worked.

The error logged on the console is:

01/12/2015 17:21:35.309 Lattice[19311]: ctlconvert error: code 1, modulepath: "/Users/login/Library/Containers/biz.lut.Lattice/Data/Library/Application Support/biz.lut.Lattice/aces-1.0-ctl" details: Unable to read tiff file: /var/folders/jx/dqy9l91d44z1my_q0spwd2x00000gn/T/biz.lut.Lattice/biz.lut.Lattice/AE26E498-5282-4331-BB4F-19E83BDC9D37-19311-00000BDB9A63FE98_file.exr: No such file or directoryunable to read file /var/folders/jx/dqy9l91d44z1my_q0spwd2x00000gn/T/biz.lut.Lattice/biz.lut.Lattice/AE26E498-5282-4331-BB4F-19E83BDC9D37-19311-00000BDB9A63FE98_file.exr (unknown format).

**Comment by gregcotten** [comment]
Oh dear! Thanks for catching that. Time for a patch! I'll try to fix tonight.




Greg

**Comment by Nick-Shaw** [comment]
Am I at the mercy of App Store approval to get the patch? Is it possible for me to migrate from being an App Store customer to being a direct customer?

Nick

**Comment by gregcotten** [comment]
Unfortunately I don't have an answer for that one yet. We are working on it!
