### ISSUE TITLE
More Batch options

### ISSUE THREAD

**Issue by frankjonen** [videovillage/Lattice-Issues#53]
When you have a few hundred LUTs to convert from one colour space to another it would be helpful to be able to do that in batch.

**Example:**
- I have a 1D camera LUT
- I have several 3D grade LUTs

> To convert all of those against the 1D, I'd like to just set the one LUT I want to apply to a folder of LUTs (sub-folder recursive toggle), then set how I want to apply the 1D (in my case it's mostly 'behind') and let the script run. 

**UI suggestion:**
1. Select folder of LUTs (check 'include subfolders' if applicable)
2. Select the LUT to apply to the previously selected
3. Set method of combining (Combine, Combine Below, Mix - one setting for all)
4. Run (button)

That way it's easy to re-run on a few source LUTs without having to start over again. The same process could also be used to render out preview images.

This would make a very tedious manual process quite a breeze.

**Comment by gregcotten** [comment]
Hi Frank,

I’ve had the idea for applying transforms before batch exporting for a
while now - wasn’t sure if many people would find it useful! Certainly
something I can look in to!

Greg

**Comment by frankjonen** [comment]
Hi Greg,

for me it'd be huge. I'm sure on-set DITs would appreciate it too for quickly converting looks to match A/B cameras. 

Frank

**Comment by gregcotten** [comment]
well, better late than never! It's in 1.7
