### ISSUE TITLE
Export approximate look CDL and XML not producing any file

### ISSUE THREAD

**Issue by andyp6** [videovillage/Lattice-Issues#54]
Hi Guys,

I just tried saving using the 'export approximate look' option in 1.5.5 and neither option (.cc and .xml) is saving anything to disk. I'm on Mavericks.

**Comment by gregcotten** [comment]
Hello,

Sorry about that! We don't test on Mavericks anymore so testing new features is hard. Would you mind opening Console.app, searching for Lattice, and copying/pasting recent entries here?

Thanks!
Greg

**Comment by gregcotten** [comment]
I think I just tracked down the issue - it should be fixed in an upcoming
release!

Greg

**Comment by gregcotten** [comment]
Fixed in 1.5.6!
