### ISSUE TITLE
Error message opening a .lut

### ISSUE THREAD

**Issue by icifredo** [videovillage/Lattice-Issues#56]
Hello

Trying to open a .lut, I have this :+1: 
**\* -[NSArray subarrayWithRange:]: range {0, 9223372036854775807} extends beyond bounds [0 .. 4914]

Any idea ?

**Comment by icifredo** [comment]
as code :
`*** -[NSArray subarrayWithRange:]: range {0, 9223372036854775807} extends beyond bounds [0 .. 4914]`

**Comment by gregcotten** [comment]
Hello! Unfortunately not all .lut files are created equal - many
manufacturers casually share the same file extension but do not share the
same spec. For example, the .lut format we support is the Discreet 1D LUT
format. Feel free to send the file to support@videovillage.co and I can
take a look at it!
