### ISSUE TITLE
openable LUT for Autodesk

### ISSUE THREAD

**Issue by REM6392** [videovillage/Lattice-Issues#58]
Hello,
i whant to save LUT in Autodesk format (.3dl).
i try with any option i find in Lattice (Lustre, Flamme, Legacy ...ect) but Smoke do not open neither of them ...
Thanx to help me

**Comment by gregcotten** [comment]
Hello,

What version of Smoke are you running? Also what version of Lattice are you
running?

Thanks!
Greg

**Comment by REM6392** [comment]
Hello Greg,



I use Smoke 2015.0.3 and Lattice 1.5.7.

best regards.

 

Berge Rémi
62 Av. Marguerite Renaudin
92140 Clamart
0671008471
berge@orange.fr

**Comment by gregcotten** [comment]
Berge,

Are you able to open a .cube or .3dl using the syncolor Colour Transform
option instead of 3D LUT or 1D LUT?

**Comment by gregcotten** [comment]
Also are you getting any errors in the console when trying to open any of
the .3dl files?

**Comment by REM6392** [comment]
Hello Greg,



i can open .cube with the Colour Transform
option but not .3dl (made with Lattice but Autodesk native, yes).

see message error.

best regards.

 

Berge Rémi
62 Av. Marguerite Renaudin
92140 Clamart
0671008471
berge@orange.fr
