### ISSUE TITLE
please add export support for convergent design odyssey (CDLUT) format

### ISSUE THREAD

**Issue by sincohen** [videovillage/Lattice-Issues#59]

**Comment by gregcotten** [comment]
Hello,

Convergent Design doesn't seem to have any documentation on their format.
I'm not sure how I can support it - I'll reach out in the next week and see
what they can do.

**Comment by sincohen** [comment]
Great,
I think they will be able to give you the information on how to support the format. Live grade can export for it and CD seems to enjoy having widely supported and workflow compatible devices. I could also provide some cubes and CDLUTS as exported out of live grade if you think you could use that to backwards engineer it.

s

**Comment by gregcotten** [comment]
I've received the spec and am working on it. Definitely poorly documented but hopefully I'll have something soon!

**Comment by sincohen** [comment]
thanks for the awesome support.
s

**Comment by gregcotten** [comment]
Done and in 1.5.8!
