### ISSUE TITLE
Batch export of Approximate CDL/XML

### ISSUE THREAD

**Issue by sincohen** [videovillage/Lattice-Issues#60]
Please allow batch processing/export support for CDLs

**Comment by gregcotten** [comment]
Hi,

You can drag CDLs into the batch exporter now!

**Comment by sincohen** [comment]
I mean,
Ability to batch export TO cdl/cc.
so for instance, take a bunch of .cube and have them batch exported to CDL through the lovely and so far very accurate approximation system you have. So far as i can tell the export to option only includes the standard supported LUT formats, no CC/CDL options.

thanks,
s

**Comment by gregcotten** [comment]
Ah, yes I understand.

**Comment by gregcotten** [comment]
Done and in the next release.
