### ISSUE TITLE
ACES Proxy, ACEScc and AP0 and AP1

### ISSUE THREAD

**Issue by giardiello** [videovillage/Lattice-Issues#62]
Hi, 
I would like to ask if there is any plan to include support for ACES Primaries 1 (I believe that what is called ACES now in the software it actually corresponds to AP0) and for ACEScg and ACEScc curves characterizations. 
So one will be able to create LUT's to convert from ACES proxy AP1 to ACES 2065 AP0, for instance.

Hope it makes sense,
Best regards,
Francesco Giardiello

**Comment by gregcotten** [comment]
Hi Francesco,

I'll need to brush up on my ACES knowledge - I might be a bit behind in
that regard. I can certainly add those curves and primaries! For the
moment, I believe all that can be done with CTL from the ACES github -
certainly could and should be implemented in Lattice, though!

Greg

**Comment by giardiello** [comment]
It can be done via CTL indeed, but is for whom doesn't have access to CTL files. I guess it could be made quickly if the math was integrated within the software. 

Thanks a lot,
F.

**Comment by timkang1980** [comment]
I was just about to ask for this! Thanks Francesco!

**Comment by gregcotten** [comment]
@timkang1980 Do you know where I can find the numbers for AP0 and AP1?

**Comment by giardiello** [comment]
From ACES AMPAS repositories
On 20 Sep 2016 9:43 p.m., Greg Cotten <notifications@github.com> wrote:@timkang1980 Do you know where I can find the numbers for AP0 and AP1?

**Comment by gregcotten** [comment]
@giardiello

Of course I know that! Digging through isn't too fun though.

**Comment by giardiello** [comment]
Look for ACEScc.
You will find them there. 
On 20 Sep 2016 9:59 p.m., Greg Cotten <notifications@github.com> wrote:@giardiello

Of course I know that! Digging through isn't too fun though.

**Comment by gregcotten** [comment]
All I'm seeing are matrices which aren't helpful unless @tashdor would like
to derive the primaries from them?

**Comment by KelSolaar** [comment]
@gregcotten : You can grab them all from Colour here if you don't want to fiddle with the AMPAS documents: https://github.com/colour-science/colour/blob/develop/colour/models/rgb/dataset/aces.py

**Comment by gregcotten** [comment]
@KelSolaar Thanks so much! Just what I was looking for.

**Comment by gregcotten** [comment]
Done.
