### ISSUE TITLE
Apple App Store doesn't show my App as purchase

### ISSUE THREAD

**Issue by chromaticpictures** [videovillage/Lattice-Issues#65]
Hi Ben,
Don't know if this is a intended Glitch in the Appstore but your Application doesn't show up as a app that can be moved to another computer. I was able to do it via the separate email you sent me some time back to install the app with the License key. Just checking if this is just the way you have set it up. Thanks and happy new year!

**Comment by gregcotten** [comment]
Hi there! Not sure if this is a problem on our end. You can't "move" a Mac App Store app to another computer - you have to log in to the App Store on each computer you wish to put Lattice onto and download it from there.

Greg
