### ISSUE TITLE
Feature Request: LUT to Lightroom

### ISSUE THREAD

**Issue by elliotttate** [videovillage/Lattice-Issues#66]
First of all, I think Lattrice is an amazing product. Would it be possible to automatically convert a Lut to a lightroom preset? (not lightroom to lut, but the other way around). I can do this manually by using Lattrice to view all the points on a curve and then enter them into a lightroom curve, but this takes a while. Even if this isn't a perfect conversion, it looks pretty much spot on. The Lightroom preset files look very easy to work with as they just contain all the curve points in plain text. Thanks!

Brian

**Comment by gregcotten** [comment]
Hi Brian!

Sure thing. It's done. Bummer that each curve only allows 10 points of precision.

Greg

**Comment by elliotttate** [comment]
You are amazing!! Will this just show up in the next version released?

**Comment by gregcotten** [comment]
Yep!

Greg
