### ISSUE TITLE
Cineon/RedLogFilm transform in Lattice inconsistant float values when compared to ACES and OCIO transform

### ISSUE THREAD

**Issue by andyp6** [videovillage/Lattice-Issues#67]
Hi Greg,

I've been working with a VFX artist and we've had some very tiny inconsistencies when linearizing REDLogFilm and Cineon material in Nuke, Resolve and After Effects (if using Lattice generated luts). 

Lattice generated RLF/Cineon to Lin 1D luts have different values to the native transforms and luts in Nuke, Resolve and After Effects (OCIO). 

ACES, Nuke, Resolve, OCIO all seem to use the following transform for both Cineon and RedLogFilm but Lattice appears to be using something slightly different. It's not really noticeable visually but shows up when comparing pixel values:

```
def cineon_to_linear(code_value):
        n_gamma = 0.6
        black_point = 95
        white_point = 685
        code_value_to_density = 0.002
```
```
        black_linear = pow(10, (black_point - white_point) * (
            code_value_to_density / n_gamma))
        code_linear = pow(10, (code_value - white_point) * (
            code_value_to_density / n_gamma))

        return (code_linear - black_linear) / (1 - black_linear)
```

(Copied from [OCIO ACES 1.0.3](https://github.com/imageworks/OpenColorIO-Configs/blob/master/aces_1.0.3/python/aces_ocio/colorspaces/red.py) ) 

This produces values that exactly match Resolve's Cineon to Linear 1d VFX lut.

If I need to use Lattice I can get around the difference with CTL but it would be great if it matched natively.

**Comment by gregcotten** [comment]
Here's the code Lattice is using.

My forward math is this:
`pow(10.0,(1023.0*value-685.0)/300.0)-.0108/(1-.0108)`

And reverse:
`(300.0*log(value+27.0/2473.0) + 685.0*log(10.0))/(1023.0*log(10.0))`

Strangely, while searching for my reverse equation online to see where I got it, I stumbled upon possibly a [post](http://www.magiclantern.fm/forum/index.php?topic=17893.msg172308#msg172308) by you (?!) in some forum with the exact same reverse equation.

I'll happily change the code! No complaints in almost 3 years is a bit mysterious.

**Comment by gregcotten** [comment]
Looks like this is what happens when you use one liners... Forward equation almost evaluates correctly except it needs to be this:
`(pow(10.0,(1023.0*value-685.0)/300.0)-.0108)/(1-.0108)`

**Comment by andyp6** [comment]
Yes, I think I lazily copy/pasted the Cineon equation from your old repo.  I think I have the inverse of the RED (Kodak) formula somewhere if you need it?

I don't think anyone noticed (including me) because the difference is so small and can often be due to different interpolation algorithms. It didn't cause any issues for me until my VFX guy had a play with DaVinci Resolve.

**Comment by gregcotten** [comment]
It's fixed and will be in the next release! Thanks so much for catching this.

**Comment by andyp6** [comment]
No worries!  :)

I think you may have originally got the Lattice formula from [this](https://www.lwks.com/index.php?option=com_kunena&func=view&catid=7&id=35030&Itemid=81#35234).

**Comment by andyp6** [comment]
Not sure if your refactored formulas are what you changed but they still don't match RLF/Cineon code values.

I get a cv match to RFL ACES IDTs, Resolve luts etc and an exact inversion to 10 significant places with:

```
Log2Lin=(pow(10,(value-685)*(0.002/0.6))-0.010797751623)/(1-0.010797751623)

Lin2Log=(LOG10(value*(1-0.010797751623)+0.010797751623)*300)+685
```

(based on 10bit int values so just divide by 1023) 

it's exact if the `black_linear` variable is computed as float math :)

**Comment by gregcotten** [comment]
Yes sorry I didn't update the equations here! Will do it now. Let me know if anything looks wrong.

**Comment by gregcotten** [comment]
Not sure how "Lin2Log" was evaluated but I'll use a simplified equation any day!

**Comment by andyp6** [comment]
> Yes sorry I didn't update the equations here! Will do it now. Let me know if anything looks wrong.

Perfect! :)
