### ISSUE TITLE
Canon Log needs scaling

### ISSUE THREAD

**Issue by andyp6** [videovillage/Lattice-Issues#69]
Hi Greg,

I think I've found another issue.

The official [C100 Mk1 CanonLog IDTs](https://www.usa.canon.com/internet/portal/us/home/support/details/cameras/cinema-eos/eos-c100) do not cancel Lattice's linear to Canon Log transform.

In lattice, the normalized 0-1 range needs to be scaled *0.9 before converting to Canon Log for the IDT to (nearly) cancel out the transform.

I [modified the IDT](https://s3-us-west-2.amazonaws.com/private03/Canon_EOS_C100_CanonLog.zip) to omit the big CPLock (3x19 matrices) and transform to ACES AP0 colorspace leaving just the transfer function if you want it for testing.

**Comment by gregcotten** [comment]
Not really sure how to proceed here as C300 IDTs don't do this...

**Comment by gregcotten** [comment]
#17

**Comment by gregcotten** [comment]
Looks like we added a scaling factor of .9 at Tim King's request #17

**Comment by gregcotten** [comment]
Taking that out makes it "cancel" perfectly

**Comment by gregcotten** [comment]
So it looks like for whatever reason C100 CanonLog doesn't use the .9 scaling factor used in the [C300 and C500 IDTs](https://github.com/ampas/aces-dev/tree/master/transforms/ctl/idt/vendorSupplied/canon). I'll need to make a CanonLog (C100) variant.

**Comment by andyp6** [comment]
Hmmm. I didn't try yet with the C300 IDTs. That does make things awkward if there are 2 'original' Canon Log variants and it gets worse because the big 3x19 matrices in the C100 IDTs are gamut shapers meaning you probably need to add the full CPLock colorspaces for C100 Clog transforms to be accurate - all assuming Canon got their IDTs perfect in the first place ;)

**Comment by gregcotten** [comment]
I can only blame Canon for this one. Generally you would want to "Gold Standard" your log equation and not sneak in changes for certain camera models.

**Comment by gregcotten** [comment]
@andyp6 Looks like the scaling is only present in the C300 mk2 IDTs...

**Comment by andyp6** [comment]
Nice of Canon to make things simple! ;)

**Comment by gregcotten** [comment]
Oh! And the scaling is present in the C500 V1.1.1 IDTs but not the V1.0 IDTs...

**Comment by andyp6** [comment]
Big mess! I'll check ACES in Resolve, Nuke etc. Chances are there are some incorrect transforms happening for some cameras.

**Comment by gregcotten** [comment]
@andyp6 any news?

**Comment by andyp6** [comment]
Sorry Greg. I haven't had a chance yet due to other work and the Easter hols. I'll get on it this week.

**Comment by gregcotten** [comment]
Not a problem! Just checking in.

**Comment by andyp6** [comment]
I've checked Resolve's IDTs vs published and self-built IDTs (using an OFX CTL plugin in Resolve) and there are several issues mainly regarding incorrect gamuts in Sony colorspaces but that's another story and not a Lattice issue. 

Lattice seems accurate to all the IDTs I have tested but I can confirm the scaling issue and the 2 versions of CanonLog also exist in Resolve. 

I also think Lattice's math for GoPro Protune Flat is likely incorrect as it doesn't seem to match this:

`x = (pow(113.0, input) - 1.0)/112.0`

taken from [David Newman's blog](http://cineform.blogspot.com/2014/03/protune-20.html)

**Comment by gregcotten** [comment]
Interesting - how are the two versions mentioned? Do they specify the camera source?

Re: GoPro - I was under the impression the gopro data needed to be scaled from legal to full first - I guess I'm now unsure of that? Anyway, I'm happy to change it back to that equation.

**Comment by gregcotten** [comment]
The other problem with ProTune is that it is a display linear equation, not scene linear equation, as far as I can tell. Not sure what to do there...

**Comment by andyp6** [comment]
Resolve has IDTs for the original C300 called **Canon C300 Daylight** and **Canon C300 Tungsten**. These incorporate the CPLOCK colorspace (3x19 matrix) - which must be included.

The C300 MkII has Daylight and Tungsten IDTs for Canon Log (scaled) and Canon Log2 in Rec2020 and Cinema gamuts.

The C100's are not supported by name in Resolve but the C100 Mk1 uses the original C300 IDTs. The C100 MkII IDT is Canon Log (scaled) + the CPLOCK colorspace and there is no IDT for that in Resolve.

re: ProTune. I thought the same (still do) but in absence of an alternative official formula I would suggest sticking with David Newman's equation as it is also being used in the official ACES 1.0.3 OCIO config (albeit tagged as 'experimental'). 

You probably have this but ProTune (lin2log) is:

`log(x*(113-1)+1,113)`

... and you're gonna hate me now (sorry) but ADX10 and ADX16 are complex (non-linear) colorspaces. There are no uses for a gamma independent version that I can find a use for outside of ACES - which uses the full colorspace.

**Comment by gregcotten** [comment]
Thanks! I'll probably call the original "CanonLog  X (Unscaled)" as I'm thinking (hoping) most people are going to be using the new C300, C500, or C700. And yep, that's the reverse I have, but it's always good for confirmation.

No hate at alI! I have little/no interest in ADX10 or ADX16 but I had a customer request it (transfer function decoupled) and I obliged!

**Comment by gregcotten** [comment]
Also regarding ADX, the only color space transformation inside ADX10 to ACES is a [3x3 matrix](https://github.com/ampas/aces-dev/blob/ed0c686a2067ee1daf60178fecc88633a0af26dc/transforms/ctl/csc/ADX/ACEScsc.ADX10_to_ACES.ctl#L18) applied after the log to scene linear math / lookups. Theoretically I could derive (if not already known) the primaries from that matrix and add it into Lattice as a colorspace. Let me know what I'm missing!

**Comment by andyp6** [comment]
re: CanonLog X - sounds good!

re: ADX primaries from that matrix (assuming a x0.33 y0.33 neutral white point) are:

`
r 0.8441	0.1392
g 0.1299	0.7857
b 0.1288	0.0996
`

OCIO does it like [this](https://github.com/hpd/OpenColorIO-Configs/blob/master/aces_1.0.3/config.ocio#L128)

**Comment by gregcotten** [comment]
Fixed, by the way!

**Comment by andyp6** [comment]
Great! Thanks Greg :)
