### ISSUE TITLE
Batch import tool request

### ISSUE THREAD

**Issue by mikelafuente** [videovillage/Lattice-Issues#70]
I would love to see a batch import tool added to the product to compliment the batch export.  I get into situations where I have to convert 30-35 LUTs into 5 other formats. I currently do this with some opensource command line tools, but this app has the most format options.

**Comment by gregcotten** [comment]
Hi! Check out File->Batch Export LUTs... (at the very bottom). Drag and drop as many LUTs or folders of LUTs into the list, and click "Export".

![screen shot 2017-05-31 at 5 35 02 pm](https://cloud.githubusercontent.com/assets/924470/26659843/d3ee3ede-4628-11e7-8701-cb6fd123d198.png)
