### ISSUE TITLE
App Store versions not keeping up with Standalone releases

### ISSUE THREAD

**Issue by andyp6** [videovillage/Lattice-Issues#71]
Hi guys,

I needed to build a fairly complex lut today that would have made use of a feature added in 1.7.1 (Canon log - the scaling issue I reported) but The App Store version is lagging significantly behind the Standalone i.e. The App Store version is still on 1.7.0 and the Standalone is already 1.7.2. Some versions are also never released. I ended up building the lut with scripting which took me much longer than dialing in a few settings in Lattice.

Can I migrate to the Standalone?

Thanks.

**Comment by gregcotten** [comment]
Please email us and we can get that started for you.

Greg

**Comment by gregcotten** [comment]
support@videovillage.co

**Comment by andyp6** [comment]
Emailing now. Thanks Greg!
