### ISSUE TITLE
ICC Profile Class "Input" instead of "Display" for Capture One

### ISSUE THREAD

**Issue by elliotttate** [videovillage/Lattice-Issues#72]
You do an incredible job updating Lattice - thank you!! I use Lattice to convert LUTs to Capture One using ICC Profiles, but Capture One seems to only read it if it has a class "Input" not "Display" like Lattice creates. I can get around it by batch changing a HEX value, but is their anyway you can add this option when batch exporting LUTs? Thanks so much!!

Brian

**Comment by gregcotten** [comment]
Hi Brian! Thanks so much! Do you know what hex value you are changing? That
might help clue me in on what I need to do to make it work.

**Comment by elliotttate** [comment]
Sure! It's just changing mntr to scnr as seen on the screenshot. Thanks!!

![icc](https://user-images.githubusercontent.com/25666454/30825536-5486e774-a201-11e7-9159-72cda96220bd.jpg)

**Comment by gregcotten** [comment]
Elliot - I believe this feature has been added - you should be able to switch between Display and Input class when exporting an ICC.
