### ISSUE TITLE
ASC-CDL implementation seems only to clamp final output

### ISSUE THREAD

**Issue by Nick-Shaw** [videovillage/Lattice-Issues#75]
According to the spec, I believe ASC-CDL is supposed to clamp 0-1 between the SOP and the saturation operations `out = Clamp((in * slope) + offset) ^ power` as well as clamping the final output. It appears to me that the implementation in Lattice only clamps the final output.

Actually this raises another issue. The ACES variation on ASC-CDL should not clamp at all, so it might be useful to add a check-box for clamping in the CDL dialog.

**Comment by gregcotten** [comment]
I never knew it was supposed to clamp at that point or any point - actually
come to think of it I don’t think I’ve read the spec - any chance you have
it? Emailing asc-cdl@theasc.com (as indicated to do on the
Wikipedia) yields a "no such email" bounceback.

>

**Comment by gregcotten** [comment]
By the way, the output clamping only occurs if you prepend - appending will not clamp because it's not applying the CDL before the LUT!

**Comment by Nick-Shaw** [comment]
https://www.dropbox.com/s/jiyr2sml8po8gy2/asc-cdl_documentation.zip?dl=1

**Comment by gregcotten** [comment]
Done!

<img width="422" alt="screen shot 2018-02-08 at 12 12 08 pm" src="https://user-images.githubusercontent.com/924470/35995801-53f71080-0cc9-11e8-9b81-1e2431b62d77.png">

**Comment by Nick-Shaw** [comment]
Nice! Now I just need to wait for the App Store update!

Do you think it might be better to explicitly call the check-box `Clamp`? If you didn't know ASC-CDL was supposed to clamp, others might not realise either. In any case, all CDL is "ASC-CDL" except the later ACES version which explicitly varies from it in order that it can be used on un-clamped float ACES 2065-1 image data. S-2016-001 says in Appendix A "To preserve the extended range of ACEScct values, no limiting function should be applied with ASC CDL parameters."

**Comment by gregcotten** [comment]
Yes maybe I should call it "Clamp". I guess the one thing that leaves it ambiguous is that it really should indicate that it clamps both steps independently and not just after the last step which is definitely different!

**Comment by gregcotten** [comment]
I should also note that I have customers that use CDL for video game development and they too do not expect a clamp to occur!

**Comment by Nick-Shaw** [comment]
I don't deny that in modern unclamped float pipelines, the option to switch off clamping is definitely beneficial. But equally there should be the option to clamp according to the original spec.

**Comment by gregcotten** [comment]
I totally agree!
