### ISSUE TITLE
Expression can not be applied

### ISSUE THREAD

**Issue by sjkgm** [videovillage/Lattice-Issues#76]
How can I enter a formula for Arri LogC to Linear in Expression?
According to ARRI's LogC Curve in VFX.pdf, it seems to be described as follows at EI 800, but the Apply button is grayed out.

(x > 0.1496582 ? pow(10.0, (x - 0.385537) / 0.2471896) : x / 0.9661776 - 0.04378604) * 0.18 - 0.00937677

**Comment by gregcotten** [comment]
Hi there! That equation doesn't look quite right. In any case, if you really want to use an expression to do this (and not the built-in colorspace converter that already has that equation built in), you would do:

if($x > 0.1496582, [result if true], [result if false])

I would highly recommend using the built-in colorspace converter like this instead:
<img width="606" alt="screen shot 2018-04-11 at 11 14 55 am" src="https://user-images.githubusercontent.com/924470/38635225-95f87cd6-3d79-11e8-9911-0d79e3a83482.png">

**Comment by sjkgm** [comment]
Hi
Thanks for your reply.
But, I do not know the syntax of this Expression. 
I would appreciate it if it is described in Help.

There is no choice but to use Expression. The reason is that it is necessary to make a LUT that linearizes EI 160 - 640 & 1000 - 1600 other than EI 800. If they are also included in the built-in Color Space converter, there is nothing wrong.

**Comment by gregcotten** [comment]
Oh gotcha.

For the EI 800 Log C to Linear expression, you would do:

`if($x > 0.149659, (pow(10,($x - 0.385537) / 0.247189) - 0.052272) / 5.555556, ($x - 0.092809) / 5.367650)`

**Comment by gregcotten** [comment]
Take a look here: https://github.com/ampas/aces-dev/blob/ed0c686a2067ee1daf60178fecc88633a0af26dc/transforms/ctl/idt/vendorSupplied/arri/alexa/v3/EI800/IDT.ARRI.Alexa-v3-logC-EI800.ctl#L10

**Comment by gregcotten** [comment]
Make sure to take out the ACES color transform unless you need it!
