### ISSUE TITLE
Viewer artifacts with 3D identity lut (odd numbers below 65x only)

### ISSUE THREAD

**Issue by andyp6** [videovillage/Lattice-Issues#78]
Hi Greg,

I've not noticed this before but the Lattice viewer shows significant artifacts when creating any new identity lut with an odd number of grids (anything below 65^3 seems to be a problem). 

An identity created with an even number of grids does not show any artifacts.

I tested the actual luts in After Effects, Resolve, Nuke etc and they seem fine but I need to be able to trust the viewer.

To reproduce load this test image https://truecolor.us/downloads/lut-stress-test-image/ and create a new 3D lut (17, 33 etc).

Will send an example if needed.

My current OS is 10.12 Sierra (via VMware - might that be the problem?). No problems with monitor calibration, ICC profiles etc.

**Comment by gregcotten** [comment]
Hello! This is a weird one. I don't have an issue here. It's possible VMWare could be the culprit? Could you send test images?

What I'm seeing:
32x
<img width="1202" alt="screen shot 2018-08-30 at 11 50 25 am" src="https://user-images.githubusercontent.com/924470/44872645-f4d5a680-ac4a-11e8-96bd-bc9874e37f7c.png">

33x
<img width="1202" alt="screen shot 2018-08-30 at 11 50 28 am" src="https://user-images.githubusercontent.com/924470/44872643-f4d5a680-ac4a-11e8-87e1-1551ed4120c0.png">

**Comment by andyp6** [comment]
I'm suspecting VMWare is the culprit here (no direct support for graphics cards) but I don't currently have access to a Mac at my location to test. 

Here's one at 33x

![identity_33x_artifacts](https://user-images.githubusercontent.com/7623740/44873429-e0bc9400-aca0-11e8-906b-0c259a1c6ee1.jpeg)

and 63x (though I would never use this size)

![identity_63x_artifacts](https://user-images.githubusercontent.com/7623740/44873475-05187080-aca1-11e8-98dd-591fe6cfdb01.jpeg)

**Comment by wilg** [comment]
Closing until we receive evidence this isn't happening due to emulation.
