### ISSUE TITLE
Export Approximate CDL crashes Lattice

### ISSUE THREAD

**Issue by jicabrera** [videovillage/Lattice-Issues#87]
Lattice 1.7.14 crashes when trying to export CDL approximation and does not save any file. Running on Mojave 10.14.5

**Comment by gregcotten** [comment]
Hi!

There is a known bug causing a crash if you export approximate CDLs through the File->Export Approximate button. As a workaround, use Edit-Analyze-Approximate CDL Values. Click Calculate CDL, then click export.

Sorry for the inconvenience! We hope to have an update fixing the problem soon.

**Comment by jicabrera** [comment]
Thank you Greg!

---
*Juan Ignacio Cabrera*
*Colorist & Stereographer*
IMDb <http://www.imdb.com/name/nm3043942>

**Comment by gregcotten** [comment]
This is fixed as of 1.8.0
