### ISSUE TITLE
ACES Panasonic CTL doesn't load in lattice

### ISSUE THREAD

**Issue by NicolasBilly** [videovillage/Lattice-Issues#88]
Hi,

I'm trying to load the ACES CTL IDT from Panasonic website, but Lattice won't accept it. 
Could you integrate this IDT into Lattice ACES config?
https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/support/index.html

Kind regards,
Nicolas Billy

**Comment by gregcotten** [comment]
Hi Nicolas,

For whatever reason Panasonic has included an import in the CTL for a library that doesn't exist. Simply delete or comment-out the line `import "utilities";` using your preferred text editor and Lattice should import it no problem.

**Comment by NicolasBilly** [comment]
Awesome! Thanks
