### ISSUE TITLE
1D lut preview is black

### ISSUE THREAD

**Issue by eweidt** [videovillage/Lattice-Issues#89]
Image preview goes entirely black when I make a new 1D lut on Lattice for Mac version 1.8 (build 1656)

Choose New Lut
Under create Identity Lut, choose 1D Lut
Size, choose any
Input bounds, 0, 1
Click OK

Image preview is black.   Now if I choose Convert to 3D lut, then the Image Preview appears normal.  Now choosing Convert to 1D lut, preview will go back to black.

I've tried this with 16 and 8 bit TIFF, also Jpeg and PNG images.  Saving the image out will also yield an entirely black image.

Note all of the above is with Unity settings, ie., a straight line in the Curve preview.

**Comment by gregcotten** [comment]
Hi!

What Mac and macOS are you using? We’ve seen issues with VMs and
Hackintoshes occasionally.

**Comment by eweidt** [comment]
Hi GregThank you - I'm on a recent Macbook Pro - OS X Sierra 10.12.6 - screenshot attached.
CheersEric
    On Thursday, September 5, 2019, 4:23:27 PM PDT, Greg Cotten <notifications@github.com> wrote:  
 
 Hi!

What Mac and macOS are you using? We’ve seen issues with VMs and
Hackintoshes occasionally.

**Comment by gregcotten** [comment]
Eric,

Quick fix is to update to macOS 10.13 High Sierra or macOS 10.14 Mojave (or macOS 10.15 Catalina in two weeks). I don't have a Sierra install handy, so I will have to check it when I have time to install on an old Mac.
