### ISSUE TITLE
More Primaries / Pro Photo RGB

### ISSUE THREAD

**Issue by wellcome86** [videovillage/Lattice-Issues#92]
Hi Could you add Pro Photo RGB in the Primaries ? so Fotos with that ICC Profile will be treated correct.

You could also add a free choosable Primaries via ICC Profiles 

thanks

**Comment by gregcotten** [comment]
Hello! ProPhoto RGB is already included in the primaries.

<img width="228" alt="Screen Shot 2019-12-04 at 6 07 14 PM" src="https://user-images.githubusercontent.com/924470/70197495-e8978f00-16c0-11ea-85a4-6ac61764e7c8.png">

**Comment by egsell24** [comment]
This may have been discussed elsewhere, but if not I'll drop it right here.  It would be nice to allow for the creation of arbitrary primaries, for non-standard color spaces, wither for input, output, or both.
