### ISSUE TITLE
Cann't open .cube LUT file

### ISSUE THREAD

**Issue by DP-Huanhuan** [videovillage/Lattice-Issues#99]
All my *.cube LUT can't be opened. Error message says "Lattice cannot open files in the 'Custom look up table file' format. 
It seems to be a version 1.8.18 (1834) only issue. Older version works fine.

**Comment by gregcotten** [comment]
No issues with that on any of our test Macs... what macOS version are you running?

**Comment by DP-Huanhuan** [comment]
Latest macOS which is 12.5. Hardware is M1 MacBook 13 2020. A friend of mine had the same issue.

**Comment by gregcotten** [comment]
Do you have another LUT application installed? I'm not sure what "Custom look up table file" is even supposed to be - we don't describe .cube LUTs like that in our imported "Unique Type Identifiers". Could be some app claiming ownership over that format.

**Comment by DP-Huanhuan** [comment]
Oh you are right. I uninstalled the DJI ronin app and it works. Thanks.
